from fpdf import FPDF
from datetime import datetime
import re

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'MinuteMind AI', 0, 1, 'C')
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'Meeting Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by MinuteMind AI', 0, 0, 'C')

def clean_text_for_fpdf(text):
    """Replaces bullet points and other unicode characters unsupported by default FPDF latin-1."""
    if not text:
        return ""
    # Replace common unicode characters
    text = text.replace('•', '-')
    text = text.replace('→', '->')
    text = text.replace('’', "'")
    text = text.replace('‘', "'")
    text = text.replace('“', '"')
    text = text.replace('”', '"')
    text = text.replace('–', '-')
    text = text.replace('—', '-')
    
    # Encode to latin-1 and ignore bad chars
    return text.encode('latin-1', 'replace').decode('latin-1')

def extract_topic(mom_text):
    """Attempts to extract the topic from MoM."""
    match = re.search(r'Topic:\s*(.*)', mom_text)
    if match:
        return match.group(1).strip()
    return "Not detected"

def extract_attendees(mom_text):
    """Attempts to extract attendees from MoM."""
    match = re.search(r'Attendees:\s*(.*)', mom_text)
    if match:
        return match.group(1).strip()
    return "Not detected"
    
def generate_pdf(transcript, llm_sections, output_path="meeting_report.pdf"):
    """Generates a PDF report based on the provided format."""
    
    pdf = PDF()
    pdf.add_page()
    pdf.set_font("Arial", size=11)
    
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M:%S")
    
    topic = extract_topic(llm_sections.get('mom', ''))
    
    # Header Details
    pdf.cell(0, 8, f"Date: {date_str}", 0, 1)
    pdf.cell(0, 8, f"Time: {time_str}", 0, 1)
    pdf.cell(0, 8, f"Meeting Topic: {clean_text_for_fpdf(topic)}", 0, 1)
    pdf.ln(5)
    pdf.cell(0, 0, "-"*100, 0, 1, 'C')
    pdf.ln(5)
    
    # 1. Meeting Transcript
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "1. Meeting Transcript", 0, 1)
    pdf.set_font("Arial", size=10)
    pdf.multi_cell(0, 6, clean_text_for_fpdf(transcript))
    pdf.ln(5)
    pdf.cell(0, 0, "-"*100, 0, 1, 'C')
    pdf.ln(5)
    
    # 2. Meeting Summary
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "2. Meeting Summary", 0, 1)
    pdf.set_font("Arial", size=10)
    pdf.multi_cell(0, 6, clean_text_for_fpdf(llm_sections.get('summary', '')))
    pdf.ln(5)
    pdf.cell(0, 0, "-"*100, 0, 1, 'C')
    pdf.ln(5)
    
    # 3. Key Discussion Points
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "3. Key Discussion Points", 0, 1)
    pdf.set_font("Arial", size=10)
    pdf.multi_cell(0, 6, clean_text_for_fpdf(llm_sections.get('key_points', '')))
    pdf.ln(5)
    pdf.cell(0, 0, "-"*100, 0, 1, 'C')
    pdf.ln(5)
    
    # 4. Action Items
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "4. Action Items", 0, 1)
    pdf.set_font("Arial", size=10)
    pdf.multi_cell(0, 6, clean_text_for_fpdf(llm_sections.get('action_items', '')))
    pdf.ln(5)
    pdf.cell(0, 0, "-"*100, 0, 1, 'C')
    pdf.ln(5)
    
    # 5. Minutes of Meeting (MoM)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "5. Minutes of Meeting (MoM)", 0, 1)
    pdf.set_font("Arial", size=10)
    pdf.multi_cell(0, 6, clean_text_for_fpdf(llm_sections.get('mom', '')))
    pdf.ln(5)
    pdf.cell(0, 0, "-"*100, 0, 1, 'C')
    pdf.ln(5)
    
    # 6. Next Meeting Details (Optional)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "6. Next Meeting Details (Optional)", 0, 1)
    pdf.set_font("Arial", size=10)
    pdf.cell(0, 6, "Date: ", 0, 1)
    pdf.cell(0, 6, "Time: ", 0, 1)
    pdf.ln(5)
    pdf.cell(0, 0, "-"*100, 0, 1, 'C')
    pdf.ln(5)
    
    pdf.output(output_path)
    return output_path
